mnist_ann & fashion_mnist_ann
pskcci/intel-01 pull request #140
Opened 2024-02-19 07:38 UTC by bluenight12

2024-02-19 12:19 UTC, J-WBaek requested changes
.ipynb_checkpoints 폴더를 제외하고 올려주세요.

2024-02-19 23:54 UTC, bluenight12 commented
> .ipynb_checkpoints 폴더를 제외하고 올려주세요.

수정 완료 했습니다

2024-02-20 00:24 UTC, elddy0948 approved these changes
readme...

2024-02-20 00:27 UTC, J-WBaek approved these changes

2024-02-20 00:27 UTC, merged